export const tableData = {
  title: 'POLYGON Network',
  heading: ['Pool Provider', 'LP', 'Reward Tokens', 'INFO'],
  rows: [
    ['Kyber DMM           ', `<a href="polygon/kyber"           >Various</a>`, 'KNC          ', 'https://dmm.exchange'],
    [
      'Quickswap           ',
      `<a href="polygon/quick"           >Various</a>`,
      'QUICK        ',
      'https://quickswap.exchange/#/quick',
    ],
    [
      'Cometh              ',
      `<a href="polygon/cometh"          >Various</a>`,
      'MUST         ',
      'https://swap.cometh.io/#/stake',
    ],
    ['Dark                ', `<a href="polygon/dark"            >Various</a>`, 'DB           ', 'https://www.dark.build'],
    ['Smartdex *          ', `<a href="polygon/smartdex"        >Various</a>`, 'NIOX         ', 'https://swap.smartdex.app'],
    ['Elk                 ', `<a href="polygon/elk"             >Various</a>`, 'ELK          ', 'https://app.elk.finance'],
    ['Polywhale           ', `<a href="polygon/polywhale"       >Various</a>`, 'KRILL        ', 'https://polywhale.finance'],
    ['Aave                ', `<a href="polygon/aave"            >Various</a>`, 'MATIC        ', 'https://aave.com'],
    ['BullionFinance             ', `<a href="polygon/bullionfinance"         >Various</a>`, 'GOLD          ', 'https://bullionfinance.xyz'],
    ['Polyfox             ', `<a href="polygon/polyfox"         >Various</a>`, 'FOX          ', 'https://polyfox.finance'],
    ['Hawkdex             ', `<a href="polygon/hawk"            >Various</a>`, 'HAWK         ', 'https://hawkdex.com'],
    ['PolyDragon          ', `<a href="polygon/polydragon"      >Various</a>`, 'FIRE         ', 'https://polydragon.io'],
    ['Polycat             ', `<a href="polygon/polycat"         >Various</a>`, 'FISH         ', 'https://polycat.finance'],
    ['BoughtThe.top       ', `<a href="polygon/boughtthetop"    >Various</a>`, 'BTT          ', 'https://farm.BoughtThe.top'],
    ['PolyStarter         ', `<a href="polygon/polystarter"     >Various</a>`, 'STARTER      ', 'https://www.polystarter.fi'],
    ['Polyvolve           ', `<a href="polygon/polyvolve"       >Various</a>`, 'SPEAR        ', 'https://polyvolve.finance'],
    ['Polygaj             ', `<a href="polygon/polygaj"         >Various</a>`, 'GAJ          ', 'https://polygaj.finance'],
    [
      'Galaxy              ',
      `<a href="polygon/galaxy"          >Various</a>`,
      'Various      ',
      'https://galaxyfarm.routerprotocol.com',
    ],
    [
      'GameSwap            ',
      `<a href="polygon/gameswap"        >Various</a>`,
      'STONK        ',
      'https://gameswapfinance.com',
    ],
    [
      'Blackswap           ',
      `<a href="polygon/blackswap"       >Various</a>`,
      'AURORA/SOLAR ',
      'https://www.blackswap.finance',
    ],
    [
      'Polycake            ',
      `<a href="polygon/polycake"        >Various</a>`,
      'PCAKE        ',
      'https://www.polycake.finance',
    ],
    [
      'Polyrangers         ',
      `<a href="polygon/polyrangers"     >Various</a>`,
      'RNG          ',
      'https://polyrangers.finance',
    ],
    ['Sushi               ', `<a href="polygon/sushi"           >Various</a>`, 'SUSHI        ', 'https://app.sushi.com'],
    ['Mai                 ', `<a href="polygon/mai"             >Various</a>`, 'Qi           ', 'https://www.mai.finance'],
    [
      'Polyshark           ',
      `<a href="polygon/polyshark"       >Various</a>`,
      'SHARK        ',
      'https://www.polyshark.finance',
    ],
    [
      'Polyvalent          ',
      `<a href="polygon/polyvalent"      >Various</a>`,
      'ELECTRON     ',
      'https://www.polyvalent.finance',
    ],
    ['Polyfi              ', `<a href="polygon/polyfi"          >Various</a>`, 'PolyFi       ', 'https://polyfi.io'],
    ['Polyape             ', `<a href="polygon/polyape"         >Various</a>`, 'Ape          ', 'https://www.polyape.online'],
    [
      'Polyzap             ',
      `<a href="polygon/polyzap"         >Various</a>`,
      'PZAP         ',
      'https://farm.polyzap.finance',
    ],
    ['Gemstones Finance   ', `<a href="polygon/gemstonesfinance">Various</a>`, 'GMS          ', 'https://gemstones.finance'],
    ['Polypanda           ', `<a href="polygon/polypanda"       >Various</a>`, 'BAMBOO       ', 'https://polypanda.finance'],
    [
      'Dfyn *              ',
      `<a href="polygon/dfyn"            >Various</a>`,
      'DFYN         ',
      'https://exchange.dfyn.network',
    ],
    [
      'Jurassic            ',
      `<a href="polygon/jurassic"        >Various</a>`,
      'RAPTOR       ',
      'https://www.jurassicfarm.app',
    ],
    [
      'Beefy               ',
      `<a href="polygon/beefy"           >Various</a>`,
      'Various      ',
      'https://polygon.beefy.finance',
    ],
    [
      'Monopoly            ',
      `<a href="polygon/monopoly"        >Various</a>`,
      'MONO         ',
      'https://monopolyfinance.xyz',
    ],
    ['Polyce              ', `<a href="polygon/polyce"          >Various</a>`, 'CSI          ', 'https://polyce.io'],
    ['Lumberjack          ', `<a href="polygon/lumberjack"      >Various</a>`, 'ACORN        ', 'https://lumberjack.finance'],
    ['PolyPunk            ', `<a href="polygon/polypunk"        >Various</a>`, 'PPNK         ', 'https://polypunk.finance'],
    ['SteakHouse          ', `<a href="polygon/steakhouse"      >Various</a>`, 'STEAK        ', 'https://steakhouse.finance'],
    ['Monke Farm          ', `<a href="polygon/monkefarm"       >Various</a>`, 'MONKE        ', 'https://monkefarm.finance'],
    ['Polylion            ', `<a href="polygon/polylion"        >Various</a>`, 'LION         ', 'https://polylion.exchange'],
    ['PolyBull            ', `<a href="polygon/polybull"        >Various</a>`, 'BULL         ', 'https://polybull.finance'],
    ['Orcinus             ', `<a href="polygon/orcinus"         >Various</a>`, 'ORCA         ', 'https://www.orcinuslabs.ca'],
    [
      'Polyape Finance     ',
      `<a href="polygon/polyape_finance" >Various</a>`,
      'APE          ',
      'https://www.polyapefinance.com',
    ],
    ['PolyWolf            ', `<a href="polygon/polywolf"        >Various</a>`, 'WOLF         ', 'https://polywolf.finance'],
    ['Stacker Ventures    ', `<a href="polygon/stacker-vc"      >Various</a>`, 'STACK        ', 'https://stacker.vc'],
    [
      'Polygoat            ',
      `<a href="polygon/polygoat"        >Various</a>`,
      'GOAT         ',
      'https://www.polygoat.finance',
    ],
    [
      'Polysnake           ',
      `<a href="polygon/polysnake"       >Various</a>`,
      'SNAKE        ',
      'https://www.polysnake.finance',
    ],
    ['Moonwolf            ', `<a href="polygon/moonwolf"        >Various</a>`, 'MOON         ', 'https://www.moonwolf.io'],
    [
      'Iron *              ',
      `<a href="polygon/iron"            >Various</a>`,
      'TITAN        ',
      'https://polygon.iron.finance',
    ],
    [
      'Alchemy Dao         ',
      `<a href="polygon/alchemydao"      >Various</a>`,
      'ALCH         ',
      'https://polygon.alchemydao.com',
    ],
    ['Polycrab            ', `<a href="polygon/polycrab"        >Various</a>`, 'CRAB         ', 'https://polycrab.finance'],
    ['Polybear            ', `<a href="polygon/polybear"        >Various</a>`, 'BEAR         ', 'https://polybear.exchange'],
    ['StonkFarm           ', `<a href="polygon/stonkfarm"       >Various</a>`, 'STONKX       ', 'https://stonk.farm'],
    ['Polydex             ', `<a href="polygon/polydex"         >Various</a>`, 'PLX          ', 'https://polydex.fi'],
    ['PolyMaple           ', `<a href="polygon/polymaple"       >Various</a>`, 'MAPLE        ', 'https://www.polymaple.com'],
    ['Gravity Finance     ', `<a href="polygon/gravityfinance"  >Various</a>`, 'GFI          ', 'https://gravityfinance.io'],
    [
      'Smellycat           ',
      `<a href="polygon/smellycat"       >Various</a>`,
      'PUSSY        ',
      'https://www.smellycat.finance',
    ],
    ['Polygold            ', `<a href="polygon/polygold"        >Various</a>`, 'POLYGOLD     ', 'https://polygold.finance'],
    [
      'Polyswan            ',
      `<a href="polygon/polyswan"        >Various</a>`,
      'SWAN         ',
      'https://www.polyswan.finance',
    ],
    ['Polyion             ', `<a href="polygon/polyion"         >Various</a>`, 'LION         ', 'https://www.polyion.net'],
    ['Eleven              ', `<a href="polygon/eleven"          >Various</a>`, 'ELE          ', 'https://eleven.finance'],
    ['Pirate Dice         ', `<a href="polygon/piratedice"      >Various</a>`, 'BOOTY        ', 'http://piratedice.xyz'],
    ['PolyPingu           ', `<a href="polygon/polypingu"       >Various</a>`, 'PINGU        ', 'https://polypingu.finance'],
    [
      'Goldenbull          ',
      `<a href="polygon/goldenbull"      >Various</a>`,
      'GBULL        ',
      'https://farms.goldenbull.finance',
    ],
    ['Polyakita           ', `<a href="polygon/polyakita"       >Various</a>`, 'HACHI        ', 'https://defi.polyakita.com'],
    [
      'Prism               ',
      `<a href="polygon/prism"           >Various</a>`,
      'PRISM        ',
      'https://polygon.prismfinance.net',
    ],
    [
      'Polybutterfly       ',
      `<a href="polygon/polybutterfly"   >Various</a>`,
      'POLLEN       ',
      'https://polybutterfly.finance',
    ],
    ['Southpark           ', `<a href="polygon/southpark"       >Various</a>`, 'SOUTHPARK    ', 'https://southpark.finance'],
    ['PolyCash            ', `<a href="polygon/polycash"        >Various</a>`, 'CASH         ', 'https://polycash.finance'],
    [
      'Dinosaur            ',
      `<a href="polygon/dinosaur"        >Various</a>`,
      'DINO         ',
      'https://dinosaurfinance.vercel.app',
    ],
    ['Magic               ', `<a href="polygon/magic"           >Various</a>`, 'DRAX/NIGHT/DMAGIC  ', 'https://defimagic.io'],
    ['Polymouse           ', `<a href="polygon/polymouse"       >Various</a>`, 'MICE         ', 'https://polymouse.finance'],
    ['PolyTiger           ', `<a href="polygon/polytiger"       >Various</a>`, 'TIGON        ', 'https://www.polytiger.com'],
    ['Polydeer            ', `<a href="polygon/polydeer"        >Various</a>`, 'DEER         ', 'https://polydeer.finance'],
    ['Avengers            ', `<a href="polygon/avengers"        >Various</a>`, 'SHIELD       ', 'https://avengers.exchange'],
    [
      'PolyBunny           ',
      `<a href="polygon/polybunny"       >Various</a>`,
      'BUNNY        ',
      'https://www.polybunny.finance',
    ],
    ['BerserkFinance      ', `<a href="polygon/berserkfinance"  >Various</a>`, 'BRSK         ', 'https://berserkfinance.com'],
    [
      'PolyMeme            ',
      `<a href="polygon/polymeme"        >Various</a>`,
      'MEME         ',
      'vfat.tools/polygon/polymeme',
    ],
    [
      'Museum Of Crypto Art',
      `<a href="polygon/moca"            >Various</a>`,
      'MOCA         ',
      'https://museumofcryptoart.com',
    ],
    ['PolyPup             ', `<a href="polygon/polypup"         >Various</a>`, 'PUP          ', 'https://polypup.finance'],
    [
      'Space               ',
      `<a href="polygon/space"           >Various</a>`,
      'SPACE        ',
      'https://polygon.space-defi.com',
    ],
    ['Glock               ', `<a href="polygon/glock"           >Various</a>`, 'GLOCK        ', 'https://www.glockswap.com'],
    [
      'XDollar             ',
      `<a href="polygon/xdollar"         >Various</a>`,
      'XDO          ',
      'https://xdollar.mcn.ventures',
    ],
    [
      'PolyCarrot          ',
      `<a href="polygon/polycarrot"      >Various</a>`,
      'CARROT       ',
      'https://www.polycarrot.finance',
    ],
    ['8Ball               ', `<a href="polygon/8ball"           >Various</a>`, '8BALL        ', 'https://8ballfinance.io'],
    ['MordorSwap          ', `<a href="polygon/mordorswap"      >Various</a>`, 'MORDOR       ', 'https://mordorswap.finance'],
    ['PolyVertex          ', `<a href="polygon/polyvertex"      >Various</a>`, 'VERT         ', 'https://polyvertex.finance'],
    ['PolyZero            ', `<a href="polygon/polyzero"        >Various</a>`, 'ZERO         ', ''],
    ['PolyMax             ', `<a href="polygon/polymax"         >Various</a>`, 'MAX          ', 'https://polymax.club'],
    ['PolySnowFarm        ', `<a href="polygon/polysnowfarm"    >Various</a>`, 'SNOW         ', 'https://polysnow.farm'],
    ['Polyyeld *          ', `<a href="polygon/polyyeld"        >Various</a>`, 'YELD/xYELD   ', 'https://polyyeld.finance'],
    ['Polysa              ', `<a href="polygon/polysa"          >Various</a>`, 'DUFF         ', 'https://www.polysa.finance'],
    [
      'Wault               ',
      `<a href="polygon/wault"           >Various</a>`,
      'WEXpoly      ',
      'https://app.wault.finance/polygon/',
    ],
    [
      'PolyHarvest         ',
      `<a href="polygon/polyharvest"     >Various</a>`,
      'WHEAT        ',
      'https://www.polyharvest.finance',
    ],
    [
      'PolyWoof            ',
      `<a href="polygon/polywoof"        >Various</a>`,
      'TREAT        ',
      'https://www.polywoof.finance',
    ],
    ['SafeDollar *        ', `<a href="polygon/safedollar"      >Various</a>`, 'SDS/SDO      ', 'https://app.safedollar.fi'],
    [
      'Cosmic              ',
      `<a href="polygon/cosmic"          >Various</a>`,
      'COSMIC       ',
      'https://polygon.cosmicswap.finance',
    ],
    ['StonkYFarm          ', `<a href="polygon/stonky"          >Various</a>`, 'STONKY       ', 'https://stonky.farm'],
    ['Polycafe            ', `<a href="polygon/polycafe"        >Various</a>`, 'JAVA         ', 'https://polycafe.finance'],
    ['Slowpoke            ', `<a href="polygon/slowpoke"        >Various</a>`, 'SLOW         ', 'https://slowpoke.space'],
    [
      'PolyRocket          ',
      `<a href="polygon/polyrocket"      >Various</a>`,
      'ROCKET       ',
      'https://www.rocketfarming.finance',
    ],
    ['PolyComet           ', `<a href="polygon/polycomet"       >Various</a>`, 'COMET        ', 'https://www.polycomet.com'],
    ['KogeFarm                ', `<a href="polygon/koge"            >Various</a>`, 'Various      ', 'https://kogefarm.io'],
    [
      'Fulcrum             ',
      `<a href="polygon/fulcrum"         >Various</a>`,
      'PGOV         ',
      'https://polygon.fulcrum.trade',
    ],
    ['XBull               ', `<a href="polygon/xbull"           >Various</a>`, 'XBULL        ', 'https://xbull.finance'],
    ['Augury              ', `<a href="polygon/augury"          >Various</a>`, 'OMEN         ', 'https://augury.finance'],
    ['PolyMeme V2         ', `<a href="polygon/polymemev2"      >Various</a>`, 'MEME         ', 'https://polyme.me'],
    [
      'WorldSwap Bali      ',
      `<a href="polygon/worldswap_dps"   >Various</a>`,
      'DPS          ',
      'https://bali.worldswap.finance',
    ],
    ['PolyFunky Finance   ', `<a href="polygon/polyfunky"       >Various</a>`, 'FUNK         ', 'https://www.polyfunky.com'],
    ['Polycuban           ', `<a href="polygon/polycuban"       >Various</a>`, 'CUBAN        ', 'https://polycuban.finance'],
    ['50Cent              ', `<a href="polygon/50c"             >Various</a>`, '50C/50K      ', 'https://50cent.network'],
    ['HonestWorkFarms     ', `<a href="polygon/honestwork"      >Various</a>`, '🚜          ', 'https://www.honestwork.farm'],
    ['Adamant             ', `<a href="polygon/adamant"         >Various</a>`, 'Various      ', 'https://adamant.finance'],
    ['Polygame            ', `<a href="polygon/polygame"        >Various</a>`, 'POLYGAME     ', 'https://polygame.finance'],
    ['Carousel            ', `<a href="polygon/carousel"        >Various</a>`, 'CRS          ', 'https://carouselswap.com'],
    [
      'PolyCrystal         ',
      `<a href="polygon/polycrystal"     >Various</a>`,
      'CRYSTAL      ',
      'https://polycrystal.finance',
    ],
    [
      'Firebird            ',
      `<a href="polygon/firebird"        >Various</a>`,
      'HOPE         ',
      'https://app.firebird.finance',
    ],
    ['Polyroll            ', `<a href="polygon/polyroll"        >Various</a>`, 'ROLL         ', 'https://polyroll.org'],
    ['FarmHero            ', `<a href="polygon/farmhero"        >Various</a>`, 'HONOR        ', 'https://farmhero.io'],
    ['PolyYield           ', `<a href="polygon/polyyield"       >Various</a>`, 'YIELD        ', 'https://polyyield.finance'],
    [
      'PolyPulsar          ',
      `<a href="polygon/polypulsar"      >Various</a>`,
      'BPUL         ',
      'https://www.polypulsar.farm',
    ],
    [
      'Lego                ',
      `<a href="polygon/lego"            >Various</a>`,
      'LEGO         ',
      'https://legofarming-polygon.club',
    ],
    ['FairyFarming        ', `<a href="polygon/fairy"           >Various</a>`, 'FAIRY        ', 'https://fairyfarming.world'],
    ['Rediant             ', `<a href="polygon/rediant"         >Various</a>`, 'RDT          ', 'https://rediant.finance'],
    ['StonkZFarm          ', `<a href="polygon/stonkzfarm"      >Various</a>`, 'STONKZ       ', 'https://stonkz.farm'],
    ['NinjaSwap           ', `<a href="polygon/ninjaswap"       >Various</a>`, 'NINJA        ', 'https://ninjaswapdefi.com'],
    ['Polyquity           ', `<a href="polygon/polyquity"       >Various</a>`, 'PYQ          ', 'https://app.polyquity.org'],
    ['Tako                ', `<a href="polygon/tako"            >Various</a>`, 'TAKO         ', 'https://takodefi.com'],
    ['Harvester           ', `<a href="polygon/harvester"       >Various</a>`, '🌾          ', 'https://harvester.app'],
    [
      'Polymer             ',
      `<a href="polygon/polymer"         >Various</a>`,
      'OIL          ',
      'https://polymeryield.finance',
    ],
    ['Polybrew            ', `<a href="polygon/polybrew"        >Various</a>`, 'BREW         ', 'https://polybrew.finance'],
    [
      'PolyDiamond         ',
      `<a href="polygon/polydiamond"     >Various</a>`,
      'DMND         ',
      'https://polydiamondfinance.com',
    ],
    ['PolyCactus          ', `<a href="polygon/polycactus"      >Various</a>`, 'CACTUS       ', 'https://polycactus.com'],
    ['PolyGrass           ', `<a href="polygon/polygrass"       >Various</a>`, 'GRASS        ', 'https://polygrass.online'],
    ['Pickle              ', `<a href="polygon/pickle"          >Various</a>`, 'PICKLE       ', 'https://app.pickle.finance'],
    ['Fox                 ', `<a href="polygon/fox"             >Various</a>`, 'FOX          ', 'https://foxfarming.us'],
    ['MountainSwap        ', `<a href="polygon/mountainswap"    >Various</a>`, 'MOUNTAIN     ', '                     '],
    ['Hippolygon          ', `<a href="polygon/hippolygon"      >Various</a>`, 'HIPPO        ', 'https://hippolygon.com'],
    ['Pepe                ', `<a href="polygon/pepe"            >Various</a>`, 'PEPEFARM     ', 'https://pepefarm.finance'],
    [
      'PolyPupBone         ',
      `<a href="polygon/polypupbone"     >Various</a>`,
      'BONE         ',
      'https://bone.polypup.finance',
    ],
    [
      'PolyRhino           ',
      `<a href="polygon/polyrhino"       >Various</a>`,
      'HORN         ',
      'https://polyrhino.vercel.app',
    ],
    [
      'PolyRuby            ',
      `<a href="polygon/polyruby"        >Various</a>`,
      'RUBY         ',
      'https://www.polyruby.finance',
    ],
    ['PolyZeus            ', `<a href="polygon/polyzeus"        >Various</a>`, 'PolyZeus     ', 'https://polyzeus.finance'],
    ['PolyMax - CaveMan   ', `<a href="polygon/polymax_caveman" >Various</a>`, 'CaveMan      ', 'https://caveman.polymax.club'],
    ['PolyTreasure        ', `<a href="polygon/polytreasure"    >Various</a>`, 'TRZ          ', 'https://vfat.tools/polygon/polytreasure'],
    ['PolyRacoon          ', `<a href="polygon/polyracoon"      >Various</a>`, 'RACOON       ', 'https://polyracoon.com/'],
    ['BoneSwap            ', `<a href="polygon/boneswap"        >Various</a>`, 'BONE         ', 'https://farm.boneswap.finance'],
    ['Polyyearn           ', `<a href="polygon/polyyearn"       >Various</a>`, 'YEARN        ', 'https://polyyearn.finance'],
    ['WorldSwap Hanoi     ', `<a href="polygon/worldswap_han"   >Various</a>`, 'HAN          ', 'https://hanoi.worldswap.finance'],
    ['Astrobunny          ', `<a href="polygon/astrobunny"      >Various</a>`, 'ABUNNY       ', 'https://www.astrobunny.finance'],
    ['BisonFinance        ', `<a href="polygon/bisonfinance"    >Various</a>`, 'BISON        ', 'https://bisonfinance.online'],
    ['Bullrun             ', `<a href="polygon/bullrun"         >Various</a>`, 'BULL         ', 'https://polygon.bullrun.finance'],
    ['PolyArrow           ', `<a href="polygon/polyarrow"       >Various</a>`, 'ARROW        ', 'https://polyarrow.xyz'],
    ['PantsuSwap          ', `<a href="polygon/pantsuswap"      >Various</a>`, 'PANTSU       ', 'https://pantsuswap.com'],
    ['PolyMocha           ', `<a href="polygon/polymocha"       >Various</a>`, 'MOCHA        ', 'https://polymocha.finance'],
    ['PolyOwl             ', `<a href="polygon/polyowl"         >Various</a>`, 'OWL          ', 'https://www.polyowl.finance'],
    ['Astrofarms - Cancer ', `<a href="polygon/astrofarmscancer">Various</a>`, 'CANCER       ', 'https://cancer.astrofarms.finance'],
    ['FaunaFinance        ', `<a href="polygon/faunafinance"    >Various</a>`, 'FAUNA        ', 'https://www.fauna.finance'],
    ['Vampire             ', `<a href="polygon/vampire"         >Various</a>`, 'VAMPIRE      ', 'https://vampirefarming.club'],
    ['PolyGorilla         ', `<a href="polygon/polygorilla"     >Various</a>`, 'GORILLA      ', 'https://polygorilla.finance'],
    ['PolyGarden          ', `<a href="polygon/polygarden"      >Various</a>`, 'APPLE        ', 'https://www.polygarden.finance'],
    ["Gains Farm          ", `<a href="polygon/gains-farm"      >GFARM2/DAI</a>`,"GFARM2     ", "https://gains.farm"],
    ['DojoFarmFinance     ', `<a href="polygon/dojofarm"        >Various</a>`, 'DOJO         ', 'https://dojofarm.finance'],
    ['PolyMaple-MapleSyrup', `<a href="polygon/polymaplesyrup"  >Various</a>`, 'SYRUP        ', 'https://www.polymaple.com'],
    ['PolyTopia           ', `<a href="polygon/polytopia"       >Various</a>`, 'UTOPIA       ', 'https://polytopia.farm'],
    ['BrainSwap           ', `<a href="polygon/brainswap"       >Various</a>`, 'BRAIN        ', 'https://brainswap.finance'],
    ['BatSwap             ', `<a href="polygon/batswap"         >Various</a>`, 'BATSWAP      ', 'https://batswap.finance'],
    ['ChickenFarms        ', `<a href="polygon/chickenfarms"    >Various</a>`, 'CHICKEN      ', 'https://chickenfarms.live'],
    ['Polyfrenchie        ', `<a href="polygon/Polyfrenchie"    >Various</a>`, 'pFRE         ', 'https://polyfrenchie.com/?network=polygon'],
    ['ChickenFarms        ', `<a href="polygon/chickenfarms"    >Various</a>`, 'CHICKEN      ', 'https://chickenfarms.live'],
    ['Polycuppa           ', `<a href="polygon/polycuppa"       >Various</a>`, 'CUPPA        ', 'https://polycuppa.finance'],
    ['Polymax - Berkshire ', `<a href="polygon/polymax_berkshire">Various</a>`, 'BERKSHIRE   ', 'https://berkshire.polymax.club'],
    ['Platinum Finance    ', `<a href="polygon/platinumfinance" >Various</a>`, 'PLATIN       ', 'https://platinumfinance.app'],
    ['Iridium Finance     ', `<a href="polygon/iridiumfinance"  >Various</a>`, 'IRIDIUM      ', 'https://iridiumfinance.app/'],
    ['Platinum Finance    ', `<a href="polygon/platinumfinance" >Various</a>`, 'PLATIN       ', 'https://platinumfinance.app'],
    ['DuckFarm            ', `<a href="polygon/duckfarm"        >Various</a>`, 'DUCK         ', 'https://duckfarm.one'],
    ['PolyCow             ', `<a href="polygon/polycow"         >Various</a>`, 'MILK         ', 'https://polycow.finance'],
    ['Euroballz           ', `<a href="polygon/euroballz"       >Various</a>`, 'BALLZ        ', 'https://euroballz.finance'],
    ['JetSwap             ', `<a href="polygon/jetswap"         >Various</a>`, 'pWINGS       ', 'https://polygon.jetswap.finance'],
    ['PolyToken           ', `<a href="polygon/polytoken"       >Various</a>`, 'POLYTOKEN    ', 'https://polytoken.finance'],
    ['CupidSwap           ', `<a href="polygon/cupidswap"       >Various</a>`, 'CUPID        ', 'https://www.cupidswap.com'],
    ['PolyTulip           ', `<a href="polygon/polytulip"       >Various</a>`, 'TULIP        ', 'https://www.polytulip.com'],
    ['PolyHeaven          ', `<a href="polygon/polyheaven"      >Various</a>`, 'BIBLE        ', 'https://polyheaven.finance'],
    ['PolyGhost           ', `<a href="polygon/polyghost"       >Various</a>`, 'GHOST        ', 'https://polyghost.finance'],
    ['SecuraFinance       ', `<a href="polygon/securafinance"   >Various</a>`, 'SCR          ', 'https://polygon.secura.finance'],
    ['LotusSwap           ', `<a href="polygon/lotusswap"       >Various</a>`, 'ROYAL        ', 'https://polygon.lotusswapdefi.com'],
    ['LoveCupidSwap       ', `<a href="polygon/cupidswaplove"   >Various</a>`, 'LOVE         ', 'https://www.lovecupidswap.live'],
    ['PharmSwap           ', `<a href="polygon/pharmswap"       >Various</a>`, 'PHARM        ', 'https://pharmswap.finance'],
    ['WorldSwap Community Edition', `<a href="polygon/worldswap_community"   >Various</a>`, 'COMMUNITY', 'https://community.worldswap.finance'],
    ['PolyQuail           ', `<a href="polygon/polyquail_kwil"  >Various</a>`, 'KWIL         ', 'https://kwil.polyquail.finance'],
    ['Coinopolis          ', `<a href="polygon/coinopolis"      >Various</a>`, 'CCASH        ', 'https://coinopolis.io'],
    ['Yearnit             ', `<a href="polygon/yearnit"         >Various</a>`, 'YEARNIT      ', 'https://yearnit.finance'],
    ['WePiggy             ', `<a href="polygon/wepiggy"         >Various</a>`, 'WPC          ', 'https://polygon.wepiggy.com/markets'],
    ['Copycat             ', `<a href="polygon/copycat"         >Various</a>`, 'FISH         ', 'https://copycat.farm'],
    ['Cakecrypt           ', `<a href="polygon/cakecrypt"       >Various</a>`, 'pCAKECRYPT   ', 'https://poly.cakecrypt.io'],
    ['TitanBull           ', `<a href="polygon/tbull"           >Various</a>`, 'TBULL        ', 'https://titanbull.finance'],
    ['Lion                ', `<a href="polygon/lion"            >Various</a>`, 'LION         ', 'https://lionfarming.cc'],
    ['PolyWantsACracker   ', `<a href="polygon/polywantsacracker">Various</a>`, 'LITHIUM     ', 'https://polywantsacracker.farm'],
    ['PolygonFarm Finance ', `<a href="polygon/polygonfarm"     >Various</a>`, 'SPADE        ', 'https://polygonfarm.finance'],
    ['Polyheat            ', `<a href="polygon/polyheat"        >Various</a>`, 'HEAT         ', 'https://polyheat.finance'],
    ['Swap Net            ', `<a href="polygon/swapnet"         >Various</a>`, 'SWP          ', 'https://swap.net'],
    ['PaprPrintr          ', `<a href="polygon/paprprintr"      >Various</a>`, 'PRNTR        ', 'https://polygon.paprprintr.finance'],
    ['PolyElysm           ', `<a href="polygon/polyelysm"       >Various</a>`, 'ELYSM        ', 'https://elysm.polytopia.farm'],
    ['Poolsar             ', `<a href="polygon/poolsar"         >Various</a>`, 'STAR         ', 'https://poolsar.finance'],
    ['Polymax - Cyborg    ', `<a href="polygon/polymax_cyborg"  >Various</a>`, 'ROBOCOP      ', 'https://cyborg.polymax.club'],
    ['PolyPonzi           ', `<a href="polygon/polyponzi"       >Various</a>`, 'PPZ          ', 'https://polyponzi.money'],
    ['MisfitSwap          ', `<a href="polygon/misfit"          >Various</a>`, 'SKULL        ', 'https://www.misfitswap.live'],
    ['DinoSwap            ', `<a href="polygon/dinoswap"        >Various</a>`, 'DINO         ', 'https://dinoswap.exchange'],
    ['Swamp               ', `<a href="polygon/swamp"           >Various</a>`, 'pSWAMP       ', 'https://swamp.finance/polygon'],
    ["SpacePortDeFi       ", `<a href="polygon/spaceport"       >Various</a>`, "STARSHIP     ", "https://polygon.spaceportdefi.com"],
    ['PolyTide            ', `<a href="polygon/polytide"        >Various</a>`, 'OYSTER       ', 'https://polytide.finance'],
    ['Copycat2            ', `<a href="polygon/copycat2"        >Various</a>`, 'FISH2        ', 'https://copycat2.farm'],
    ['Cremepie            ', `<a href="polygon/cremepie"        >Various</a>`, 'CPIE         ', 'https://cremepieswap.finance'],
    ['KUNAIFarm           ', `<a href="polygon/kunaifarm"       >Various</a>`, 'KUNAI        ', 'https://kunai.dojofarm.finance'],
    ['PolyFalcon          ', `<a href="polygon/polyfalcon"      >Various</a>`, 'FALCON       ', 'https://polyfalcon.com'],
    ['BCharity            ', `<a href="polygon/bcharity"        >Various</a>`, 'GIVE         ', 'https://bcharity.net'],
    ['BlackSwan           ', `<a href="polygon/blackswan"       >Various</a>`, 'SWAN         ', 'https://app.blackswan.network'],
    ['PolyBass            ', `<a href="polygon/polybass"        >Various</a>`, 'BASS         ', 'https://polybass.farm'],
    ['PolyBakerySwap      ', `<a href="polygon/polybakeryswap"  >Various</a>`, 'BAKE         ', 'https://www.bakery-swap.finance'],
    ['PolyTail            ', `<a href="polygon/polytail"        >Various</a>`, 'POLYTAIL     ', 'https://polytail.farm'],
    ['PearZap             ', `<a href="polygon/pearzap"         >Various</a>`, 'PEAR         ', 'https://pearzap.com'],
    ['Astrofarms - Neptune', `<a href="polygon/astrofarmsneptune">Various</a>`,'NEPTUNE      ', 'https://neptune.astrofarms.finance'],
    ['Cygnus Finance      ', `<a href="polygon/cygnusfinance"   >Various</a>`, 'CYGNUS       ', 'https://www.cygnusdefi.com'],
  ],
}