export const logos = [
  {
    name: "1inch",
    src: "https://app.1inch.io/assets/favicon/favicon-32x32.png",
  },
  {
    name: "Aave",
    src: "https://aave.com/favicon32.ico",
  },
  {
    name: "Alchemix",
    src: "https://app.alchemix.fi/static/media/AlchemixLogo.af98983b.png",
  },
  {
    name: "Alpha DEX",
    src: "https://www.kitten.finance/apple-touch-icon.png",
  },
  {
    name: "Armor",
    src: "https://armor.fi/favicon-32x32.png",
  },
  {
    name: "Badger",
    src: "https://app.badger.finance/assets/badger-logo.png",
  },
  {
    name: "Bao",
    src: "https://www.bao.finance/static/media/bao-logo.a4ad9ffb.png",
  },
  {
    name: "Cover Protocol",
    src: "https://app.coverprotocol.com/favicon.ico",
  },
  {
    name: "DFX",
    src: "https://v0.dfx.finance/favicon.ico?v=0.1",
  },
  {
    name: "Dynamic Set Dollar",
    src: "https://dsd.finance/app/favicon.ico",
  },
  {
    name: "Elena",
    src: "https://app.elena.finance/static/media/elena.3df33307.png",
  },
  {
    name: "Empty Set Dollar",
    src: "https://app.emptyset.finance/favicon.ico",
  },
  {
    name: "Float",
    src: "https://floatprotocol.com/favicon.ico",
  },
  {
    name: "Frax Finance",
    src: "https://app.frax.finance/static/media/FRAX_Logo_White.e2bdd44d.svg",
  },
  {
    name: "Inverse",
    src: "https://www.inverse.finance/assets/inverse.png",
  },
  {
    name: "Kyber",
    src: "https://dmm.exchange/favicon.png",
  },
  {
    name: "Lift.Kitchen",
    src: "https://app.lift.kitchen/logo192.png",
  },
  {
    name: "MITH Cash",
    src: "https://mith.cash/static/media/mithCash.18c4ff38.svg",
  },
  {
    name: "PowerIndex",
    src: "https://powerindex.io/favicon-32x32.png",
  },
  {
    name: "* Shiba Swap *",
    src: "https://shibaswap.com/static/media/shibaswap-icon.ee749b42.png",
  },
  {
    name: "Stabilize",
    src: "https://www.stabilize.finance/images/icon.png",
  },
  {
    name: "TrueFi",
    src: "https://app.truefi.io/favicon.ico",
  },
  {
    name: "Typhoon Cash",
    src: "https://typhoon.cash/_nuxt/img/logo-without-name.5b6c1c7.svg",
  },
  {
    name: "Unicly",
    src: "https://www.app.unic.ly/favicon.ico",
  },
  {
    name: "xSigma",
    src: "https://app.xsigma.fi/favicon.ico",
  },
  {
    name: "Basket DAO",
    src: "https://static.coincost.net/logo/cryptocurrency/basketdao.png",
  },
  {
    name: "Bella Protocol",
    src: "https://bella.fi/favicon-16x16.png",
  },
  {
    name: "Force DAO",
    src: "https://www.forcedao.com/favicon-32x32.png",
  },
  {
    name: "Harvest Finance",
    src: "https://harvest.finance/favicon-32x32.png",
  },
  {
    name: "yAxis",
    src: "https://global-uploads.webflow.com/60108e77601bb54eb6e09486/603445793a3da4ab9136abb4_favicon.png",
  },
  {
    name: "Basis",
    src: "https://basis.cash/favicon-32x32.png?v=d5f4770499f89fa40d3a46251370fb4d",
  },
  {
    name: "Basis Gold",
    src: "https://static.debank.com/image/project/logo_url/basisgold/dc226cdaa9fa88431eff6eea5667e179.png",
  },
  {
    name: "Benchmark",
    src: "https://launchpad.benchmarkprotocol.finance/favicon.png",
  },
  {
    name: "Big Data Protocol",
    src: "https://www.bigdataprotocol.com/favicon.ico?v=2",
  },
  {
    name: "Cryptex",
    src: "https://app.cryptex.finance/favicon.svg",
  },
  {
    name: "Fei",
    src: "https://fei.money/favicon.ico",
  },
  {
    name: "Ichi",
    src: "https://www.ichi.farm/favicon.ico",
  },
  {
    name: "Keep",
    src: "https://dashboard.keep.network/favicon.ico",
  },
  {
    name: "Launchpool",
    src: "https://app.launchpool.xyz/favicon/favicon.svg",
  },
  {
    name: "Optionroom",
    src: "https://app.optionroom.finance/favicon/favicon-32x32.png",
  },
  {
    name: "Pickle",
    src: "https://pickle.finance/favicon.ico",
  },
  {
    name: "Ruler Protocol",
    src: "https://app.rulerprotocol.com/logo192.png",
  },
  {
    name: "Siren",
    src: "https://ucarecdn.com/8956d15e-6fa6-4c83-9447-af91e2a85717/",
  },
  {
    name: "StakeDAO",
    src: "https://stakedao.org/favicon.ico",
  },
  {
    name: "Sushiswap",
    src: "https://app.sushi.com/_next/image?url=%2Flogo.png&w=32&q=75",
  },
  {
    name: "Universe",
    src: "https://dao.universe.xyz/favicon-32x32.png",
  },
  {
    name: "Unslashed",
    src: "https://app.unslashed.finance/logo-192.png",
  },
  {
    name: "Wasabix",
    src: "https://wasabix.finance/static/media/wasabix_king.cd8faebe.png",
  },
  {
    name: "xToken",
    src: "https://xtoken.cafe/logo192.png",
  },
  {
    name: "Yam",
    src: "https://yam.finance/favicon.ico",
  },
  {
    name: "Synthetix",
    src: "https://staking.synthetix.io/images/favicon.ico",
  },
  {
    name: "Alphr.Finance",
    src: "https://defibench.com/images/6074608e0509d.jpeg",
  },
  {
    name: "Arth",
    src: "https://arthcoin.com/ARTH.png",
  },
  {
    name: "BIOPset",
    src: "https://biopset.com/favicon.ico",
  },
  {
    name: "Daiq",
    src: "https://daiq.io/favicon.ico",
  },
  {
    name: "Debase",
    src: "https://debaseonomics.io/favicon.ico",
  },
  {
    name: "Dopex",
    src: "https://app.dopex.io/favicon-32x32.png",
  },
  {
    name: "Gamestop",
    src: "https://www.gamestop.finance/favicon.png",
  },
  {
    name: "Indexed",
    src: "https://indexed.finance/favicon.svg",
  },
  {
    name: "Morph",
    src: "https://morph.finance/assets/media/logos/favicon.ico",
  },
  {
    name: "Mushrooms",
    src: "https://d5oedxduspd3v.cloudfront.net/favicon.png",
  },
  {
    name: "Narwhale",
    src: "https://narwhale.finance/500x500.png",
  },
  {
    name: "Onecash",
    src: "https://onecash.finance/farmer.png",
  },
  {
    name: "Percent",
    src: "https://percent.finance/favicon.ico",
  },
  {
    name: "Polka",
    src: "https://polkacash.finance/favicon.ico",
  },
  {
    name: "Updown",
    src: "https://updown.finance/favicon.ico",
  },
  {
    name: "Vtd",
    src: "https://vtd.finance/assets/img/logo.jpeg",
  },
  {
    name: "Xusd",
    src: "https://xusd.money/favicon.ico",
  },
  {
    name: "Quantum Set Dollar",
    src: "https://quantumset.finance/favicon.ico",
  },
  {
    name: "YflUsd",
    src: "https://yflusd.linkswap.app/favicon.png",
  },
  {
    name: "Sharedstake",
    src: "https://www.sharedstake.org/images/tokens/logo-red.svg",
  },
  {
    name: "Wolf Of Wallstreet",
    src: "https://app.wows.finance/favicon.ico",
  },
  {
    name: "Strudel",
    src: "https://strudel.finance/images/favicon.png",
  },
  {
    name: "Ethic",
    src: "https://ethic.money/favicon.ico",
  },
  {
    name: "Sandbox",
    src: "https://staking.sandbox.game/favicon.ico",
  },
  {
    name: "Sakeswap",
    src: "https://sakeswap.finance/logo.png",
  },
  {
    name: "Defiville",
    src: "https://defiville.finance/favicons/favicon-32x32.png",
  },
  {
    name: "Governor",
    src: "https://governordao.org/favicon.ico",
  },
  {
    name: "Mint",
    src: "https://stake.publicmint.com/favicon.png",
  },
  {
    name: "Proof Of Humanity",
    src: "https://uploads-ssl.webflow.com/5fd2301a2f3de083f679382b/5fd2e8678c2480bdbd3d9c85_poh-icon.svg",
  },
  {
    name: "Valueset",
    src: "https://valueset.finance/public/favicon.ico",
  },
  {
    name: "B26",
    src: "https://images.squarespace-cdn.com/content/v1/6016976ccbc71f649dac283f/1612287909993-EL30YMHFRGKJK2GSOQWT/favicon.ico?format=100w",
  },
  {
    name: "Gaia",
    src: "https://www.dollarprotocol.com/favicon.png",
  },
  {
    name: "Ludus",
    src: "https://app.playludus.io/favicon-32x32.png",
  },
  {
    name: "Olympus",
    src: "https://olympusdao.eth.link/favicon.ico",
  },
  {
    name: "Aluna",
    src: "https://farm.aluna.social/images/favicon.ico",
  },
  {
    name: "Kine",
    src: "https://kine.finance/logo.svg",
  },
  {
    name: "Visor",
    src: "https://assets.website-files.com/6084c065d284962585e47e03/608a0e08dcd05e34808caf9f_visor-favfav.png",
  },
  {
    name: "Umbria",
    src: "https://farm.umbria.network/umbriafavicon.png",
  },
  {
    name: "Ethernity",
    src: "https://ethernity.io/favicon/android-icon-192x192.png",
  },
  {
    name: "Nft20",
    src: "https://nft20.io/favicon/favicon-32x32.png",
  },
  {
    name: "Klondike",
    src: "https://klondike.finance/favicon.ico",
  },
  {
    name: "Cvi",
    src: "https://cvi.finance/favicon.ico",
  },
  {
    name: "Futureswap",
    src: "https://exchange.futureswap.com/favicon.ico",
  },
  {
    name: "Xdefi",
    src: "https://farm.xdefi.com/favicon.ico",
  },
  {
    name: "Eurxb",
    src: "http://app.eurxb.finance/static/media/logo-mini.2918aa5a.svg",
  },
  {
    name: "Swarm Network",
    src: "https://stake.myswarm.app/favicon.ico",
  },
  {
    name: "Liquity",
    src: "https://liquity.app/favicon.png",
  },
  {
    name: "Bondappetit *",
    src: "https://bondappetit.io/favicon.ico",
  },
  {
    name: "Penguin",
    src: "https://penguinswap.eth.link/favicon.png",
  },
  {
    name: "Mimo",
    src: "https://mimo.capital/static/media/logo-mimo.94ede3e3.svg",
  },
  {
    name: "Blockchain Adventurers Guild",
    src: "https://app.thisistheway.finance/favicon.png",
  },
  {
    name: "Piedao",
    src: "https://bucketeer-e05bbc84-baa3-437e-9518-adb32be77984.s3.amazonaws.com/public/images/dc44a516-c254-44cf-a3b2-d517e09ef4ba/favicon.ico",
  },
  {
    name: "Unicrypt",
    src: "https://farm.unicrypt.network/favicon.ico",
  },
  {
    name: "Centaur",
    src: "https://cntr.finance/favicon.png",
  },
  {
    name: "EPNS",
    src: "https://incentives.epns.io/favicon.ico",
  },
  {
    name: "Tornado",
    src: "https://app.tornado.cash/favicon/favicon.ico",
  },
  {
    name: "Cyclone",
    src: "https://cyclone.xyz/favicon.ico",
  },
  {
    name: "Dogen",
    src: "https://dogen.finance/favicon.png",
  },
  {
    name: "Mochi",
    src: "https://mochi.market/favicon.ico",
  },
  {
    name: "Lift kitchen",
    src: "https://app.lift.kitchen/favicon.ico",
  },
  {
    name: "CompliFi",
    src: "https://app.compli.fi/favicon.ico",
  },
  {
    name: "Smoothy",
    src: "https://smoothy.finance/favicon.ico",
  },
  {
    name: "Popsicle",
    src: "https://frapped.io/img/popsicle-circle.e1bfde99.svg",
  },
  {
    name: "Pegs",
    src: "https://pegs.cash/favicon.ico",
  },
  {
    name: "Alchemydao",
    src: "https://alchemydao.com/alchemy_square.png",
  },
  {
    name: "Kineko",
    src: "https://stake.kineko.io/img/favicon-32x32.png",
  },
  {
    name: "Oiler",
    src: "https://staking.oiler.network/favicon.ico",
  },
  {
    name: "Swipe",
    src: "https://swipe.org/images/favicons/favicon.ico",
  },
  {
    name: "Convex",
    src: "https://www.convexfinance.com/static/favicons/favicon.ico",
  },
  {
    name: "Lever",
    src: "https://lever.network/favicon.ico",
  },
  {
    name: "Fuse",
    src: "https://fuse.io/images/favicons/favicon.ico",
  },
  {
    name: "Donkey",
    src: "https://don-key.finance/assets/images/logo-don.png",
  },
  {
    name: "Wild Credit",
    src: "https://wild.credit/favicon.cd4b3ece.ico",
  },
  {
    name: "Convergence",
    src: "https://convx.conv.finance/favicon.ico",
  },
  {
    name: "Abracadabra",
    src: "https://abracadabra.money/favicon.ico",
  },
  {
    name: "Insta Dapp",
    src: "https://defi.instadapp.io/android-chrome-192x192.png",
  },
  {
    name: "Pendle",
    src: "https://app.pendle.finance/img/brandmark.beb1d2f7.svg",
  },
  {
    name: "Shiba Swap",
    src: "https://shibaswap.com/images/logo-192x192.png",
  },
  {
    name: "BambooDeFi",
    src: "https://www.bamboodefi.com/favicon.ico",
  },
  {
    name: "Emi Swap",
    src: "https://emiswap.com/favicon.ico?v=2",
  },

  { name: "Pancake", src: "https://pancakeswap.finance/favicon.ico" },
  { name: "Apeswap", src: "https://apeswap.finance/favicon.ico" },
  { name: "Autofarm", src: "https://autofarm.network/favicon.ico" },
  { name: "Bake", src: "https://www.bakeryswap.org/favicon.ico" },
  { name: "Brew", src: "https://cafeswap.finance/favicon.ico" },
  { name: "Donut", src: "https://donutdefi.com/favicon.ico" },
  { name: "Ramen", src: "https://ramenswap.finance/favicon.ico" },
  { name: "Goose", src: "https://www.goosedefi.com/favicon.ico" },
  { name: "Salt", src: "https://www.saltswap.finance/favicon.ico" },
  { name: "Soup", src: "https://soups.finance/favicon.ico" },
  { name: "Kebab", src: "https://kebabfinance.com/favicon.ico" },
  {
    name: "Kimochi",
    src: "https://kimochi.finance/assets/favicon/favicon-32x32.png",
  },
  { name: "Xoxo", src: "https://xoxo.finance/favicon.ico" },
  { name: "Nyan", src: "https://yieldnyan.com/favicon.ico" },
  { name: "bDollar", src: "https://bdollar.fi/favicon.ico" },
  { name: "Beluga", src: "https://app.beluga.fi/favicon.ico" },
  { name: "BoltDollar", src: "https://boltdollar.finance/favicon.ico" },
  { name: "Nya Cash", src: "https://nya.cash/favicon.ico" },
  { name: "YieldScienceLabs", src: "https://yieldlab.science/favicon.ico" },
  { name: "Icecream", src: "https://icecreamswap.finance/favicon.ico" },
  { name: "Mochi", src: "https://pool.mochiswap.io/favicon.ico" },
  { name: "ValueDefi", src: "https://bsc.valuedefi.io/liquid-logo.png" },
  { name: "Kickstart", src: "https://kickstart.finance/favicon.ico" },
  { name: "Boba", src: "https://bobadefi.com/favicon.ico" },
  { name: "MidasDollar", src: "https://midasdollar.fi/favicon.ico" },
  { name: "Slime", src: "https://slime.finance/assets/images/favicon.png" },
  { name: "Stakd", src: "https://app.stakd.finance/favicon.ico" },
  { name: "Glacier", src: "https://glacierswap.org/favicon.ico" },
  { name: "Alpaca", src: "https://app.alpacafinance.org/favicon.ico" },
  { name: "UFO Swap", src: "https://ufodefi.com/favicon.ico" },
  { name: "Mythic", src: "https://www.mythic.finance/static/favicon.ico" },
  {
    name: "Wault",
    src: "https://app.wault.finance/bsc/assets/images/logo/wault-logo-square2.png",
  },
  { name: "Wantanmee", src: "https://wantanmee.finance/favicon.ico" },
  { name: "Acryptos", src: "https://app.acryptos.com/favicon.ico" },
  { name: "Sashimi", src: "https://bsc.sashimi.cool/favicon.ico" },
  { name: "Beefy", src: "https://app.beefy.finance/favicon.ico" },
  { name: "Toad Swap", src: "https://toad.farm/media/favicon.ico" },
  { name: "Koala", src: "https://koaladefi.finance/favicon.ico" },
  { name: "Yoda", src: "https://yodaswap.finance/favicon.ico" },
  { name: "Taco", src: "https://taco.finance/favicon.ico" },
  { name: "Teddy", src: "https://teddy.bears.finance/favicon.ico" },
  { name: "Gemz", src: "https://www.gemz.finance/favicon.ico" },
  { name: "Pyramid", src: "https://pyramidswap.com/favicon.ico" },
  { name: "Fed", src: "https://fedswap.finance/favicon.ico" },
  { name: "Coral", src: "https://coralfarm.finance/favicon.ico" },
  { name: "Duck Money", src: "https://duck.money/favicon.ico" },
  { name: "Iron Finance", src: "https://iron.finance/favicon.png" },
  { name: "BVaults", src: "https://bvaults.fi/favicon.ico" },
  { name: "MidasGold", src: "https://midasgold.network/images/midas/logo.png" },
  { name: "Nerve", src: "https://nerve.fi/favicon.ico" },
  { name: "Hyperjump", src: "https://farm.hyperjump.fi/favicon.ico" },
  { name: "Berry", src: "https://berrydata.co/favicon.ico" },
  { name: "Belt", src: "https://belt.fi/images/icon/favicon.ico" },
  { name: "Julswap", src: "https://julswap.com/favicon.png" },
  { name: "Blueswap", src: "https://app.blueswap.finance/favicon.ico" },
  { name: "Brickchain", src: "https://brickchain.finance/favicon.png" },
  { name: "Polaris", src: "https://app.polarisdefi.io/favicon.ico" },
  { name: "Fullsail", src: "https://fullsail.finance/favicon.ico" },
  { name: "Wynaut", src: "https://wynautdefi.app/favicon.ico" },
  { name: "Meme", src: "https://memefarm.io/favicon.ico" },
  { name: "Tsuki", src: "https://tsuki.finance/favicon.ico" },
  { name: "Deflate", src: "https://deflate.finance/favicon.ico" },
  { name: "Hyrule", src: "https://app.hyruleswap.com/favicon.ico" },
  { name: "Jiggly", src: "https://www.jiggly.finance/favicon.ico" },
  { name: "Complus", src: "https://bsc.complus.exchange/favicon.png" },
  { name: "Jurassicfarm", src: "https://www.jurassicfarm.app/favicon.ico" },
  {
    name: "Swamp",
    src: "https://swamp.finance/static/frontend/img/page-header/favicon-32x32.png",
  },
  { name: "Swipe", src: "https://swipe.org/favicon.ico" },
  { name: "ApeSafe", src: "https://apesafe.finance/images/tokens/APEDOGE.png" },
  { name: "Vlad", src: "https://app.vlad.finance/favicon.ico" },
  { name: "Zcore", src: "https://finance.zcore.network/img/fevicon.png" },
  { name: "Blizzard", src: "https://blizzard.money/favicon.ico" },
  { name: "Shitz", src: "https://shitz.lol/favicon.ico" },
  { name: "Biscuit", src: "https://biscuitfarm.finance/favicon.png" },
  { name: "Runner", src: "https://bscrunner.com/favicon.ico" },
  { name: "Pumpy", src: "https://pumpy.farm/favicon.ico" },
  { name: "Knight", src: "https://www.knightsdefi.com/favicon.png" },
  { name: "Helmet", src: "https://www.helmet.insure/favicon.ico" },
  { name: "Pollo", src: "https://pollo.finance/favicon.ico" },
  { name: "Space", src: "https://farm.space/images/farm-space/favicon.png" },
  { name: "Polis", src: "https://farms.polispay.org/favicon.ico" },
  { name: "Royal", src: "https://royalswap.io/logo.png" },
  { name: "Ducks", src: "https://ducks.finance/favicon.ico" },
  { name: "Yieldbay", src: "https://yieldbay.finance/favicon.ico" },
  { name: "Ellipsis", src: "https://ellipsis.finance/favicon.ico" },
  { name: "Flex Protocol", src: "https://flexprotocol.org/favicon.ico" },
  { name: "Iceberg", src: "https://icebergdefi.com/favicon.ico" },
  { name: "yBear", src: "http://farm.ybear.finance/favicon.ico" },
  { name: "Absorber", src: "https://absorber.finance/favicon.ico" },
  { name: "Poopswap", src: "https://poopswap.finance/favicon.ico" },
  { name: "Mooncake", src: "https://mooncakeswap.finance/favicon.ico" },
  { name: "Jade", src: "https://jadedefi.com/favicon.ico" },
  { name: "Eleven", src: "https://eleven.finance/favicon.ico" },
  { name: "Yumcha", src: "https://yumcha.finance/img/yumcha.png" },
  { name: "Comos", src: "https://app.comos.finance/favicon.ico" },
  { name: "Pokemoon", src: "https://pokemoon.app/favicon.ico" },
  { name: "Octree", src: "https://octree.finance/favicon.ico" },
  { name: "Cub", src: "https://cubdefi.com/favicon.ico" },
  { name: "Muscle", src: "https://muscle.finance/favicon.ico" },
  { name: "Carrotcake", src: "https://carrotcake.fi/favicon.ico" },
  { name: "Alchemist", src: "https://www.alchemistdefi.com/favicon.ico" },
  { name: "Mozart", src: "https://mozartfinance.io/favicon.ico" },
  { name: "Hawk", src: "https://farms.hawkbsc.net/images/haw.png" },
  { name: "Tree", src: "https://app.treedefi.com/favicon.ico" },
  { name: "Voodoo", src: "https://voodoo.supra.finance/favicon.ico" },
  { name: "Biti", src: "https://www.biti.city/favicon.ico" },
  { name: "Panda", src: "https://pandayield.com/favicon.ico" },
  {
    name: "Swirl",
    src: "https://swirl.cash/wp-content/uploads/2021/03/cropped-swirl-favcon-32x32.png",
  },
  {
    name: "Squirrel",
    src: "https://squirrel.finance/assets/img/favicon/favicon-32x32.png",
  },
  { name: "Abrakadabra", src: "https://abrakadabra.tech/favicon.ico" },
  {
    name: "Cheesecake",
    src: "https://cheesecakeswap.com/static/frontend/img/page-header/favicon-32x32.png",
  },
  { name: "Rune", src: "https://rune.farm/favicon.ico" },
  { name: "Cdo", src: "https://cdo.finance/favicon.ico" },
  { name: "Printer", src: "https://printershares.finance/favicon.ico" },
  { name: "Snek", src: "https://app.farmhub.finance/favicon.ico" },
  { name: "Uranium", src: "https://app.uranium.finance/favicon.ico" },
  { name: "Bingocash", src: "https://bingocash.app/favicon.png?v=2" },
  { name: "Zex", src: "https://www.zexswap.finance/favicon.ico" },
  { name: "Dragonball", src: "https://dragonballfinance.org/favicon.ico" },
  { name: "Fulcrum", src: "https://fulcrum.trade/images/favicon-96x96.png" },
  { name: "Diamond", src: "https://app.diamondhand.fi/favicon.png" },
  { name: "Many", src: "https://manyswap.io/favicon.ico" },
  { name: "Djinn", src: "http://djinn.gold/favicon.ico" },
  { name: "Marshmallow", src: "https://marshmallowdefi.com/favicon.ico" },
  { name: "Stabilize", src: "https://www.stabilize.finance/bsc/favicon.ico" },
  { name: "Xwin", src: "https://xwin.finance/favicon.png" },
  { name: "SupraDollar", src: "https://dollar.supra.finance/favicon.ico" },
  { name: "Borshch", src: "https://borshch.finance/favicon.ico" },
  { name: "Pasta", src: "https://pastafinance.com/favicon.ico" },
  { name: "TripSwap", src: "https://tripswap.finance/favicon.ico" },
  { name: "MilkSwap", src: "https://milkswap.app/favicon.png" },
  { name: "Smokehouse", src: "https://thesmokehouse.finance/favicon.ico" },
  { name: "Pizza", src: "https://pizzafinance.app/favicon.ico" },
  { name: "Bud", src: "https://buddefi.com//favicon.ico" },
  { name: "Birthday Cake", src: "https://birthdaycake.finance/favicon.ico" },
  { name: "DankSwap", src: "https://app.dankswap.finance/favicon.ico" },
  { name: "Mouse Farm", src: "https://app.farmhub.finance/favicon.ico" },
  { name: "LlamaSwap", src: "https://llamaswap.finance/favicon.ico" },
  { name: "Dr. Mario", src: "https://drmario.finance/favicon.ico" },
  { name: "BorgSwap", src: "https://farm.borgswap.exchange/favicon.ico" },
  { name: "Soju", src: "https://sojudefi.com/favicon.ico" },
  { name: "GoatSwap", src: "https://goatswap.finance/favicon.svg" },
  { name: "BitBlocks", src: "https://bitblocks.finance/favicon.ico" },
  { name: "Takoyaki", src: "https://takoyakidefi.com/favicon.ico" },
  { name: "VeganSwap", src: "https://veganswap.finance/favicon.ico" },
  { name: "The Farming Den", src: "https://thefarmingden.com/favicon.ico" },
  { name: "ThunderSwap", src: "https://thunderswap.finance/favicon.ico" },
  { name: "PoseidonSwap", src: "https://poseidonswap.com/favicon.ico" },
  { name: "Bourbon", src: "https://bourbondefi.com/favicon.ico" },
  { name: "The Lab", src: "https://thelab.finance/favicon.ico" },
  { name: "Pepper", src: "https://old.pepr.finance/favicon.ico" },
  { name: "Pepper v2", src: "https://app.pepr.finance/favicon.ico" },
  {
    name: "Parthenon Alpha",
    src: "https://alpha.parthenon.finance/favicon.ico",
  },
  { name: "Lokum", src: "https://lokum.finance/favicon.ico" },
  { name: "Growth", src: "https://wheat.growthdefi.com/favicon.ico" },
  { name: "Neonic", src: "https://neonic.finance/favicon.png" },
  { name: "HyperFinance", src: "https://hyfi.pro/favicon.ico" },
  { name: "Cyclone", src: "https://cyclone.xyz/bsc/favicon.ico" },
  { name: "Morse", src: "https://mors.finance/favicon.ico" },
  { name: "Jazz", src: "https://jazzdefi.com/favicon.ico" },
  { name: "Defi Oasis", src: "https://defioasis.finance/favicon.ico" },
  { name: "APWars", src: "https://farms.apwars.farm/favicon.ico" },
  { name: "Evodefi", src: "https://evodefi.com/favicon.ico" },
  { name: "Phyto", src: "https://www.phyto.finance/favicon.ico" },
  { name: "Parthenon Beta", src: "https://beta.parthenon.finance/favicon.ico" },
  { name: "Grand", src: "https://www.thegrandbanks.finance/favicon.ico" },
  { name: "Gametoken", src: "https://app.gametoken.finance/favicon.ico" },
  { name: "Gengar", src: "https://www.gengarfinance.com/favicon.ico" },
  { name: "Lime", src: "https://limeswap.io/favicon.ico" },
  { name: "Olive", src: "https://olive.cash/favicon.ico" },
  { name: "Apo", src: "https://apoyield.com/favicon.ico" },
  { name: "Shrimp", src: "https://shrimpswap.finance/favicon.ico" },
  { name: "Ybearswap", src: "https://www.ybearswap.finance/favicon.ico" },
  { name: "Apache", src: "https://app.apache.finance/favicon.ico" },
  { name: "Void", src: "https://www.void.farm/favicon.ico" },
  { name: "Mango", src: "http://mangofarm.finance/favicon.ico" },
  {
    name: "Parthenon Gamma",
    src: "https://gamma.parthenon.finance/favicon.ico",
  },
  {
    name: "Defy",
    src: "https://defy.farm/inactive-farms/files/defy%20farm-favicon.png",
  },
  { name: "Bami", src: "https://app.bami.money/favicon.png" },
  { name: "Celestial", src: "https://app.celesfinance.com/favicon.ico" },
  { name: "Pandaswap", src: "https://farms.pandaswap.xyz/favicon.ico" },
  { name: "Panther", src: "https://pantherswap.com/favicon.ico" },
  { name: "dungeonswap", src: "https://dungeonswap.app/favicon.ico" },
  {
    name: "Parthenon Delta",
    src: "https://delta.parthenon.finance/favicon.ico",
  },
  { name: "Caramel *", src: "https://caramelswap.finance/favicon.ico" },
  { name: "Plumcake", src: "https://plumcake.finance/favicon.ico" },
  { name: "Wsbdapp", src: "https://farm.wsbdapp.com/favicon.ico" },
  {
    name: "Feeder",
    src: "https://app.feeder.finance/favicon/favicon-32x32.png",
  },
  { name: "Yolodraw", src: "https://yolo-token.com/images/favicon.ico" },
  { name: "Jaguar", src: "https://jaguarswap.com/favicon.ico" },
  { name: "Zombie", src: "https://zombie-farm.com/favicon.ico" },
  { name: "Degen", src: "https://degentoken.finance/favicon.ico" },
  { name: "DegenCompound", src: "https://degentoken.finance/favicon.ico" },
  {
    name: "Parthenon Epsilon",
    src: "https://epsilon.parthenon.finance/favicon.ico",
  },
  { name: "Snake", src: "https://snakedefi.com/favicon.ico" },
  { name: "Tap", src: "https://dapp.tapswap.finance/favicon-32x32.png" },
  { name: "Aot", src: "https://www.aotfinance.com/favicon.ico" },
  { name: "Mocktail", src: "https://www.mocktailswap.finance/sicon/mok.png" },
  { name: "Dogen", src: "https://dogen.finance/favicon.ico" },
  { name: "Coinswap", src: "https://coinswap.space/assets/img/favicon.png" },
  { name: "TAO DAO", src: "https://taodao.finance/favicon.ico" },
  { name: "Space Defia", src: "https://www.space-defia.com/favicon.ico" },
  {
    name: "Barbecue Swap",
    src: "https://app.barbecueswapfinance.com/favicon.ico",
  },
  { name: "Sukiyaki", src: "https://sukiyakiswap.finance/favicon.ico" },
  { name: "PrivacySwap *", src: "https://privacyswap.finance/favicon.ico" },
  { name: "Sponge", src: "https://app.sponge.finance/favicon.ico" },
  {
    name: "Blue - PlanetFinance",
    src: "https://blue.planetfinance.io/favicon.ico",
  },
  { name: "Fanatics", src: "https://fanaticsfinance.com/favicon.ico" },
  { name: "Parthenon Zeta", src: "https://zeta.parthenon.finance/favicon.ico" },
  { name: "Taiyaki", src: "https://taiyakiswap.finance/favicon.ico" },
  { name: "Superlion", src: "https://superlion.finance/favicon.ico" },
  { name: "Pulsar", src: "https://www.pulsar.farm/favicon.ico" },
  { name: "Farmwiki", src: "http://farmwiki.xyz/favicon.ico" },
  { name: "Vanillacake", src: "https://vanillacake.farm/favicon.ico" },
  { name: "Garuda", src: "https://garudaswap.finance/favicon.ico" },
  { name: "Donald", src: "https://app.donald.finance/favicon.png" },
  { name: "Smoothy", src: "https://smoothy.finance/favicon.ico" },
  { name: "Naruto", src: "https://www.narutofinance.com/favicon.ico" },
  { name: "Warden", src: "https://www.wardenswap.finance/favicon.ico" },
  { name: "Sloth", src: "https://slothfinance.com/favicon.ico" },
  { name: "Apescape", src: "https://apescape.eth.link/favicon.ico" },
  { name: "Elixir", src: "https://www.elixir-swap.io/favicon.ico" },
  { name: "Sunflower", src: "https://sunflowerfarming.us/favicon.ico" },
  { name: "Fishstix", src: "http://fishstix.finance/favicon.png" },
  { name: "Wasabix", src: "https://bsc.wasabix.finance/favicon.ico" },
  {
    name: "Naruto Uzumaki",
    src: "https://uzumaki.narutofinance.com/favicon.ico",
  },
  { name: "Lambo", src: "https://www.lambofinance.com/favicon.ico" },
  { name: "Gator", src: "https://gatorswap.xyz/favicon.ico" },
  { name: "Pureswap", src: "https://www.pureswap.finance/favicon.ico" },
  { name: "Space Defio", src: "https://www.space-defio.com/favicon.ico" },
  { name: "Parthenon Eta", src: "https://eta.parthenon.finance/favicon.ico" },
  {
    name: "Nftfy",
    src: "https://nftfy.org/static/media/nftfy-icon.4046c3b4.svg",
  },
  { name: "Gambit", src: "https://gambit.financial/favicon-32x32.png" },
  { name: "Frenchie", src: "https://frenchiedefi.com/favicon.ico" },
  { name: "Moonharvest", src: "https://moonharvest.net/favicon.ico" },
  { name: "Cobra", src: "https://www.cobrafinance.org/favicon.ico" },
  { name: "Eggplant", src: "https://eggplant.fi/favicon.ico" },
  { name: "Dumpling", src: "https://app.dumplingdefi.finance/favicon.ico" },
  { name: "Mushrooms", src: "https://mushrooms.finance/favicon.ico" },
  { name: "Punch", src: "https://www.punchdefi.com/favicon.ico" },
  { name: "Cosmic", src: "https://app.cosmicswap.finance/favicon.ico" },
  { name: "Champagne", src: "https://champagne.farm/favicon1.png" },
  { name: "Satis", src: "https://satis.finance/favicon.ico" },
  { name: "Bondappetit", src: "https://bondappetit.io/favicon.ico" },
  { name: "Project69", src: "https://farm.project69.network/favicon.ico" },
  { name: "Grizzly", src: "https://www.grizzlyswap.com/favicon.ico" },
  { name: "Friction", src: "https://friction.finance/favicon.ico" },
  { name: "Greyhound", src: "https://greyhound.farm/favicon.ico" },
  { name: "TakoDefi", src: "https://takodefi.com/favicon.ico" },
  { name: "Latte", src: "https://latteswap.finance/favicon.ico" },
  { name: "Lever", src: "https://bsc.lever.network/Staking/favicon.ico" },
  { name: "Dinopark", src: "https://dinopark.finance/favicon.ico" },
  { name: "TenFi", src: "https://ten.finance/favicon.ico" },
  { name: "YieldFields", src: "https://yieldfields.finance/favicon.ico" },
  { name: "Tiger", src: "https://www.tigerswapdefi.com/favicon.ico" },
  {
    name: "Parthenon Theta",
    src: "https://theta.parthenon.finance/favicon.ico",
  },
  { name: "Fuse", src: "https://fuse.io/favicon.ico" },
  { name: "Otter Finance", src: "https://otterdefi.com/favicon.ico" },
  { name: "Greenbelt LH", src: "https://greenbelt.finance/favicon.ico" },
  { name: "Frankenstein", src: "https://frankenstein.finance/favicon.ico" },
  { name: "Cashcow", src: "https://cashcowswap.org/favicon.png" },
  {
    name: "Tiger Finance",
    src: "https://www.tigerfinancedefi.com/favicon.ico",
  },
  { name: "Tinville", src: "https://farms.tinville.finance/favicon.ico" },
  { name: "Matisse", src: "https://app.matisse.finance/favicon.ico" },
  { name: "Cougar", src: "https://cougarswap.io/icons/favicon.ico" },
  { name: "Fluity", src: "https://fluity.finance/favicon.png" },
  { name: "Parthenon Iota", src: "https://iota.parthenon.finance/favicon.ico" },
  { name: "Croco", src: "https://crocofinance.club/favicon.ico" },
  { name: "Cinnamonroll", src: "https://cinnamonroll.fi/favicon.ico" },
  { name: "Biswap", src: "https://biswap.org/favicon.ico" },
  { name: "Godzilla", src: "https://godzillaswapdefi.com/favicon.ico" },
  { name: "Cerberus", src: "https://gocerberus.finance/favicon.ico" },
  { name: "Greenbelt NH", src: "https://nh.greenbelt.finance/favicon.ico" },
  { name: "Pulsar Beta", src: "https://beta.pulsar.farm/favicon.ico" },
  { name: "Oni", src: "https://oni.exchange/favicon.ico" },
  { name: "Ketchup", src: "https://ketchupfinance.com/favicon.ico" },
  { name: "LawnDeFi", src: "https://lawndefi.com/favicon.ico" },
  { name: "Longdrink", src: "https://longdrink.finance/favicon.ico" },
  { name: "Blaze", src: "https://blazedefi.finance/favicon.ico" },
  { name: "GreenDefi", src: "https://greendefi.finance/favicon.ico" },
  { name: "BenSwap", src: "https://benswap.finance/favicon.ico" },
  {
    name: "Parthenon Kappa",
    src: "https://kappa.parthenon.finance/favicon.ico",
  },
  { name: "ballena.io", src: "https://ballena.io/favicon.ico" },
  { name: "Hydra", src: "https://www.hydradefi.com/favicon.ico" },
  { name: "Cosmos Farm (MARS)", src: "https://mars.cosmos.farm/favicon.ico" },
  { name: "Pancakefork", src: "https://app.pancakefork.finance/favicon.ico" },
  { name: "Vesuvius", src: "https://vesuvius.finance/favicon.ico" },
  { name: "Kesef Finance", src: "https://kesef.finance/favicon.png" },
  { name: "TheKongFinance", src: "https://thekongfinance.com/favicon.ico" },
  {
    name: "Chained Farms Network (CFN)",
    src: "https://main.chainedfarms.network/favicon.ico",
  },
  {
    name: "Chained Farms Network (SFN1)",
    src: "https://sub1.chainedfarms.network/favicon.ico",
  },
  { name: "Prism", src: "https://bsc.prismfinance.net/favicon.ico" },
  { name: "Aloe", src: "https://aloeswap.com/favicon.ico" },
  { name: "TeaSwap", src: "https://app.tea-swap.finance/favicon.ico" },
  { name: "Fish", src: "https://fishswap.app/favicon.ico" },
  { name: "Bundledao", src: "https://bundledao.org/favicon.ico" },
  { name: "GuessIt", src: "https://guessit.app/favicon.ico" },
  {
    name: "Parthenon Lambda",
    src: "https://lambda.parthenon.finance/favicon.ico",
  },
  { name: "Lazymint", src: "https://lazymint.finance/favicon.ico" },
  { name: "Werewolf", src: "https://werewolf.farm/favicon.ico" },
  { name: "PinkSwap", src: "https://www.pinkswap.finance/favicon.ico" },
  { name: "ShopSwap Finance", src: "https://shopswap.finance/favicon.ico" },
  { name: "Kikko Finance", src: "https://app.kikko.finance/favicon.ico" },
  { name: "SkunkSwap", src: "https://skunkswap.finance/favicon.ico" },
  { name: "Panty", src: "https://pantyswap.yieldpanty.finance/favicon.ico" },
  { name: "Ant", src: "https://antswap.fi/favicon.ico" },
  { name: "Billhwang", src: "https://www.billhwangdefi.co/favicon.ico" },
  { name: "Lavacake", src: "https://lavacake.finance/favicon.ico" },
  { name: "B2X", src: "https://b2xtoken.io/favicon.ico" },
  { name: "Mayo", src: "https://mayoswap.com/favicon.ico" },
  {
    name: "Espresso Latte",
    src: "https://espresso.latteswap.finance/favicon.ico",
  },
  { name: "Chipshop", src: "https://chipshop.finance/favicon.ico" },
  { name: "FarmHero", src: "https://farmhero.io/favicon.ico" },
  { name: "Galaxy", src: "https://galaxydefi.finance/favicon.ico" },
  { name: "Siberian", src: "https://siberianswap.finance/favicon.ico" },
  { name: "AnoSwap", src: "https://www.anoswap.finance/favicon.ico" },
  { name: "Marmelade", src: "https://marmelade.finance/favicon.ico" },
  { name: "Kiyomi", src: "https://kiyomi.finance/favicon.ico" },
  { name: "Pearl Defi", src: "https://pearldefi.com/favicon.ico" },
  { name: "PaprPrintr", src: "https://paprprintr.finance/favicon.ico" },
  { name: "Ant/SafeAnt Defi", src: "https://antdefi.io/favicon.ico" },
  { name: "Andromeda", src: "https://www.andromedadefi.com/favicon.ico" },
  { name: "Thunderbird", src: "https://thunderbird.finance/favicon.ico" },
  { name: "VenomSwap", src: "https://www.venomswap.net/images/egg/logo.png" },
  { name: "Elephant", src: "https://app.elephantswap.finance/favicon.ico" },
  { name: "Bloodmoon", src: "https://bloodmoon.werewolf.farm/favicon.ico" },
  { name: "Blacksheep", src: "https://www.blacksheepdefi.com/favicon.ico" },
  { name: "Rice", src: "https://ricefarm.fi/favicon.ico" },
  { name: "Parthenon Mu", src: "https://mu.parthenon.finance/favicon.ico" },
  { name: "Qi Swap", src: "https://qiswap.finance/favicon.ico" },
  { name: "Dollaremon", src: "https://money-pocket.dollaremon.fi/favicon.ico" },
  {
    name: "WorldSwap Brussels",
    src: "https://brussels.worldswap.finance/favicon.ico",
  },
  { name: "Cotton Farm", src: "https://cottonfarm.app/favicon.ico" },
  { name: "Krustykrab", src: "https://krustykrab.finance/favicon.ico" },
  { name: "Alien", src: "https://aliendefi.com/favicon.ico" },
  { name: "Unown", src: "https://www.unownswap.com/favicon.png" },
  { name: "Robinhood", src: "https://app.robinhoodswap.finance/favicon.ico" },
  { name: "Zeus", src: "https://zeusfarmsdefi.com/favicon.ico" },
  { name: "Mdex", src: "https://mdex.com/favicon.ico" },
  {
    name: "MeatchFinance",
    src: "https://www.meatchfinance.com/images/egg/logo.png",
  },
  { name: "CarnageSwap", src: "https://www.carnageswap.net/favicon.ico" },
  { name: "Thoreum", src: "https://thoreum.finance/favicon.ico" },
  { name: "BTCST", src: "https://app.btcst.finance/favicon.ico" },
  { name: "SpaceBsc", src: "https://www.bsc.space-defi.com/favicon.ico" },
  {
    name: "Popit Finance",
    src: "https://assets.jibecdn.com/prod/mcdonalds/0.0.300/assets/favicon.ico",
  },
  { name: "Faxe Farm", src: "https://www.faxe.farmwiki.xyz/favicon.ico" },
  { name: "Halvar Farm", src: "https://www.halvar.farmwiki.xyz/favicon.ico" },
  { name: "Seedmoney", src: "https://app.seedmoneyfinance.com/favicon.ico" },
  { name: "WhaleFarm", src: "https://whalefarm.finance/favicon.ico" },
  { name: "Lego", src: "https://legofarming.club/favicon.ico" },
  { name: "Rediant", src: "https://rediant.finance/favicon.ico" },
  {
    name: "Ruler Protocol",
    src: "https://app.rulerprotocol.com/app/farms/favicon.ico",
  },
  { name: "Frozencake", src: "https://www.frozencake.finance/favicon.ico" },
  { name: "Fox Finance", src: "https://www.foxfinance.org/favicon.ico" },
  { name: "Cardboard Finance", src: "https://cardboard.finance/favicon.ico" },
  { name: "Yogi", src: "https://bsc.farms.yogi.fi/favicon.ico" },
  { name: "Croxswap", src: "https://app.croxswap.com/favicon.ico" },
  { name: "Tomahawk", src: "https://tomahawk.farm/favicon.ico" },
  {
    name: "Cookiebake *",
    src: "https://cookiebake.finance/assets_new/front/images/banner_img.png?123",
  },
  { name: "Supermanion", src: "https://supermanion.com/favicon.ico" },
  {
    name: "WorldSwap Berlin",
    src: "https://berlin.worldswap.finance/favicon.ico",
  },
  { name: "Fusion Finance", src: "https://fusionfinance.farm/favicon.ico" },
  { name: "Parthenon Nu", src: "https://nu.parthenon.finance/favicon.ico" },
  { name: "Rasta", src: "https://app.rasta.finance/favicon.ico" },
  { name: "Cosmos Farm (MARS)", src: "https://mars.cosmos.farm/favicon.ico" },
  { name: "Cosmos Farm (VENUS)", src: "https://venus.cosmos.farm/favicon.ico" },
  { name: "Skyline", src: "https://skylinefi.com/favicon.ico" },
  { name: "Blueballs", src: "https://www.blueballs.finance/favicon.ico" },
  { name: "Simurgh", src: "https://simurgh.finance/favicon.ico" },
  {
    name: "Yield Parrot",
    src: "https://app.yieldparrot.finance/favicon-32x32.png",
  },
  { name: "Triton", src: "https://triton.farm/favicon.ico" },
  { name: "Trident", src: "https://trident.pearldefi.com/favicon.ico" },
  { name: "Atar", src: "https://atar.finance/favicon.png" },
  { name: "Cityswap", src: "http://www.cityswap.xyz/favicon.ico" },
  { name: "Selenium", src: "https://seleniumswap.com/favicon.ico" },
  { name: "Fallout", src: "https://www.falloutfinance.com/favicon.ico" },
  { name: "Nitro", src: "https://nosfinance.com/favicon.ico" },
  { name: "Magicbeans", src: "https://magicbeans.finance/favicon.ico" },
  { name: "SymbioteSwap", src: "https://www.symbioteswap.net/favicon.ico" },
  {
    name: "Cryptosphere",
    src: "https://cryptospace.finance/images/cry/logo.png",
  },
  { name: "RetroFarms", src: "https://retrofarms.net/images/mini_logo.png" },
  { name: "LittleFox", src: "https://littlefox.finance/favicon.ico" },
  { name: "Jungle", src: "https://jungleswap.cash/favicon.ico" },
  { name: "Parachute", src: "https://parachuteswap.com/favicon.ico" },
  { name: "Magma", src: "https://www.magmacakefinance.com/favicon.ico" },
  { name: "Dexterlab", src: "https://dexterlab.finance/favicon.ico" },
  { name: "Bullrun", src: "https://bsc.bullrun.finance/favicon.ico" },
  { name: "Gold Farm", src: "https://goldfarm.app/favicon.ico" },
  { name: "CorgiSwap", src: "https://corgiswap.org/favicon.ico" },
  { name: "WhiteTeethSwap", src: "https://whiteteethswap.finance/favicon.ico" },
  { name: "KittyFarms", src: "https://kittyfarms.app/favicon.ico" },
  { name: "Moondoge", src: "https://www.moondoge.com/favicon.ico" },
  { name: "GoldenBunny", src: "https://goldenbunny.finance/favicon.png" },
  { name: "Shibance", src: "https://shibance.com/favicon.ico" },
  { name: "Hepa", src: "https://app.hepa.finance/favicon.png" },
  { name: "Sabertooth", src: "https://sabertoothswap.com/images/favicon.ico" },

  { name: "Lavaswap", src: "https://lavaswap.com/favicon.png" },
  { name: "Mdex", src: "https://ht.mdex.com/favicon.ico" },
  {
    name: "Complus",
    src: "https://heco.complus.exchange/static/media/complus.503821e6.svg",
  },
  { name: "Hecostable", src: "https://hecostable.finance/favicon.ico" },
  { name: "Booster", src: "https://booster.farm/favicon.png" },
  { name: "Mdis", src: "https://mdis.finance/favicon.png" },
  { name: "Pippi", src: "https://app.pippi.finance/favicon.ico" },
  { name: "Nut", src: "https://nut.money/favicon.ico" },
  { name: "Maki", src: "https://app.makiswap.com/favicon.ico" },
  { name: "Elk", src: "https://app.elk.finance/favicon.png" },

  { name: "EuroBallz Finance", src: "https://euroballz.finance/favicon.ico" },
  { name: "Kyber DMM", src: "https://dmm.exchange/favicon.png" },
  { name: "Quickswap", src: "https://quickswap.exchange/logo_circle.png" },
  { name: "Cometh", src: "https://swap.cometh.io/favicon.ico" },
  { name: "Dark", src: "https://www.dark.build/favicon.ico" },
  { name: "Smartdex", src: "https://swap.smartdex.app/favicon.png" },
  { name: "Elk", src: "https://app.elk.finance/favicon.ico" },
  { name: "Polywhale", src: "https://polywhale.finance/favicon.ico" },
  { name: "Aave", src: "https://aave.com/favicon.ico" },
  { name: "BullionFinance", src: "https://bullionfinance.xyz/favicon.ico" },
  { name: "Polyfox", src: "https://polyfox.finance/favicon.ico" }, //  not exisiting
  { name: "Hawkdex", src: "https://hawkdex.com/favicon.ico" },
  { name: "PolyDragon", src: "https://polydragon.io/favicon.ico" },
  { name: "Polycat", src: "https://polycat.finance/favicon.ico" },
  { name: "BoughtThe.top", src: "https://farm.BoughtThe.top/favicon.ico" },
  { name: "PolyStarter", src: "https://www.polystarter.fi/favicon.ico" },
  { name: "Polyvolve", src: "https://polyvolve.finance/favicon.ico" },
  { name: "Polygaj", src: "https://polygaj.finance/favicon.ico" },
  { name: "Galaxy", src: "https://galaxyfarm.routerprotocol.com/favicon.ico" },
  { name: "GameSwap", src: "https://gameswapfinance.com/favicon.ico" },
  {
    name: "Blackswap",
    src: "https://www.blackswap.finance/images/favicon/favicon.ico",
  },
  { name: "Polycake", src: "https://www.polycake.finance/favicon.ico" },
  { name: "Polyrangers", src: "https://polyrangers.finance/favicon.ico" },
  { name: "Sushi", src: "https://app.sushi.com/favicon.ico" },
  { name: "Mai", src: "https://www.mai.finance/favicon.a8ed6df1.ico" },
  { name: "Polyshark", src: "https://www.polyshark.finance/favicon.ico" },
  { name: "Polyvalent", src: "https://www.polyvalent.finance/favicon.ico" },
  { name: "Polyfi", src: "https://polyfi.io/favicon.ico" },
  { name: "Polyape", src: "https://www.polyape.online/favicon.ico" },
  { name: "Polyzap", src: "https://farm.polyzap.finance/favicon.ico" },
  { name: "Gemstones Finance", src: "https://gemstones.finance/favicon.ico" },
  { name: "Polypanda", src: "https://polypanda.finance/favicon.ico" },
  { name: "Dfyn", src: "https://exchange.dfyn.network/logo.png" },
  { name: "Jurassic", src: "https://www.jurassicfarm.app/favicon.ico" },
  { name: "Beefy", src: "https://polygon.beefy.finance/favicon.ico" },
  { name: "Monopoly", src: "https://monopolyfinance.xyz/favicon.ico" },
  { name: "Polyce", src: "https://polyce.io/favicon.ico" },
  { name: "Lumberjack", src: "https://lumberjack.finance/favicon.ico" },
  { name: "PolyPunk", src: "https://polypunk.finance/favicon.ico" },
  { name: "SteakHouse", src: "https://steakhouse.finance/favicon.ico" },
  { name: "Monke Farm", src: "https://monkefarm.finance/favicon.ico" },
  { name: "Polylion", src: "https://polylion.exchange/v2/favicon-128x128.png" },
  { name: "PolyBull", src: "https://polybull.finance/favicon.ico" },
  { name: "Orcinus", src: "https://www.orcinuslabs.ca/favicon.ico" },
  {
    name: "Polyape Finance",
    src: "https://www.polyapefinance.com/favicon.ico",
  },
  { name: "PolyWolf", src: "https://polywolf.finance/favicon.ico" },
  {
    name: "Stacker Ventures",
    src: "https://stacker.vc/assets/img/favicon/favicon-196x196.png",
  },
  { name: "Polygoat", src: "https://www.polygoat.finance/favicon.ico" },
  { name: "Polysnake", src: "https://www.polysnake.finance/favicon.ico" },
  { name: "Moonwolf", src: "https://www.moonwolf.io/favicon.ico" },
  { name: "Iron", src: "https://polygon.iron.finance/favicon.png" },
  {
    name: "Alchemy Dao",
    src: "https://polygon.alchemydao.com/alchemy_square.png",
  },
  { name: "Polycrab", src: "https://polycrab.finance/favicon.ico" },
  { name: "Polybear", src: "https://polybear.exchange/favicon.ico" },
  { name: "StonkFarm", src: "https://stonk.farm/favicon.ico" },
  { name: "Polydex", src: "https://polydex.fi/favicon.ico" },
  { name: "PolyMaple", src: "https://www.polymaple.com/favicon.ico" },
  {
    name: "Gravity Finance",
    src: "https://gravityfinance.io/images/favicon.png",
  },
  { name: "Smellycat", src: "https://www.smellycat.finance/favicon.ico" },
  { name: "Polygold", src: "https://polygold.finance/favicon.ico" },
  { name: "Polyswan", src: "https://www.polyswan.finance/favicon.ico" },
  { name: "Polyion", src: "https://www.polyion.net/favicon.ico" },
  { name: "Eleven", src: "https://eleven.finance/favicon.ico" },
  { name: "Pirate Dice", src: "http://piratedice.xyz/favicon.png" },
  { name: "PolyPingu", src: "https://polypingu.finance/favicon.ico" },
  { name: "Goldenbull", src: "https://farms.goldenbull.finance/favicon.ico" },
  { name: "Polyakita", src: "https://defi.polyakita.com/favicon.jpg" },
  { name: "Prism", src: "https://polygon.prismfinance.net/favicon.ico" },
  { name: "Polybutterfly", src: "https://polybutterfly.finance/favicon.ico" },
  { name: "Southpark", src: "https://southpark.finance/favicon.ico" },
  { name: "PolyCash", src: "https://polycash.finance/favicon.ico" },
  { name: "Dinosaur", src: "https://dinosaurfinance.vercel.app/favicon.ico" },
  { name: "Magic", src: "https://defimagic.io/favicon.ico" },
  { name: "Polymouse", src: "https://polymouse.finance/favicon.ico" },
  { name: "PolyTiger", src: "https://www.polytiger.com/favicon.ico" },
  { name: "Polydeer", src: "https://polydeer.finance/favicon.ico" },
  { name: "Avengers", src: "https://avengers.exchange/favicon.ico" },
  { name: "PolyBunny", src: "https://www.polybunny.finance/favicon.ico" },
  { name: "BerserkFinance", src: "https://berserkfinance.com/favicon.ico" },
  { name: "PolyMeme", src: "vfat.tools/polygon/polymeme/favicon.ico" },
  {
    name: "Museum Of Crypto Art",
    src: "https://museumofcryptoart.com/app/uploads/2021/05/cropped-cropped-Frame-144-32x32.png",
  },
  { name: "PolyPup", src: "https://polypup.finance/favicon.ico" },
  { name: "Space", src: "https://polygon.space-defi.com/favicon.ico" },
  {
    name: "Glock",
    src: "http://i1.cdn-image.com/__media__/pics/12471/logo.png",
  },
  { name: "XDollar", src: "https://xdollar.mcn.ventures/favicon.png" },
  { name: "PolyCarrot", src: "https://www.polycarrot.finance/favicon.ico" },
  { name: "8Ball", src: "https://8ballfinance.io/favicon.ico" },
  { name: "MordorSwap", src: "https://mordorswap.finance/favicon.ico" },
  { name: "PolyVertex", src: "https://polyvertex.finance/favicon.ico" },
  { name: "PolyZero", src: "/favicon.ico" },
  { name: "PolyMax", src: "https://polymax.club/favicon.ico" },
  { name: "PolySnowFarm", src: "https://polysnow.farm/favicon.ico" },
  { name: "Polyyeld", src: "https://polyyeld.finance/favicon.ico" },
  { name: "Polysa", src: "https://www.polysa.finance/favicon.ico" },
  { name: "Wault", src: "https://app.wault.finance/polygon//favicon.ico" },
  { name: "PolyHarvest", src: "https://www.polyharvest.finance/favicon.ico" },
  { name: "PolyWoof", src: "https://www.polywoof.finance/favicon.ico" },
  { name: "SafeDollar", src: "https://app.safedollar.fi/favicon.ico" },
  { name: "Cosmic", src: "https://polygon.cosmicswap.finance/favicon.ico" },
  { name: "StonkYFarm", src: "https://stonky.farm/favicon.ico" },
  { name: "Polycafe", src: "https://polycafe.finance/favicon.ico" },
  { name: "Slowpoke", src: "https://slowpoke.space/favicon.ico" },
  { name: "PolyRocket", src: "https://www.rocketfarming.finance/favicon.ico" },
  { name: "PolyComet", src: "https://www.polycomet.com/favicon.ico" },
  { name: "KogeFarm", src: "https://kogefarm.io/favicon.ico" },
  { name: "Fulcrum", src: "https://polygon.fulcrum.trade/favicon.ico" },
  { name: "XBull", src: "https://xbull.finance/favicon.ico" },
  { name: "Augury", src: "https://augury.finance/favicon.ico" },
  { name: "PolyMeme V2", src: "https://polyme.me/favicon.ico" },
  { name: "WorldSwap Bali", src: "https://bali.worldswap.finance/favicon.ico" },
  { name: "PolyFunky Finance", src: "https://www.polyfunky.com/favicon.ico" },
  { name: "Polycuban", src: "https://polycuban.finance/favicon.ico" },
  { name: "50Cent", src: "https://50cent.network/favicon.png?v=2" },
  {
    name: "HonestWorkFarms",
    src: "https://www.honestwork.farm/images/egg/logo.png",
  },
  { name: "Adamant", src: "https://adamant.finance/favicon.ico" },
  { name: "Polygame", src: "https://polygame.finance/faviconv2.png" },
  { name: "Carousel", src: "https://carouselswap.com/favicon.ico" },
  { name: "PolyCrystal", src: "https://polycrystal.finance/favicon.ico" },
  { name: "Firebird", src: "https://app.firebird.finance/favicon.ico" },
  { name: "Polyroll", src: "https://polyroll.org/favicon.ico" },
  { name: "FarmHero", src: "https://farmhero.io/favicon.ico" },
  { name: "PolyYield", src: "https://polyyield.finance/favicon.ico" },
  {
    name: "PolyPulsar",
    src: "https://www.polypulsar.farm/images/egg/PolyPulsarCoin180.png",
  },
  { name: "Lego", src: "https://legofarming-polygon.club/favicon.ico" },
  { name: "FairyFarming", src: "https://fairyfarming.world/favicon.ico" },
  { name: "Rediant", src: "https://rediant.finance/favicon.ico" },
  { name: "StonkZFarm", src: "https://stonkz.farm/favicon.ico" },
  { name: "NinjaSwap", src: "https://ninjaswapdefi.com/favicon.ico" },
  { name: "Polyquity", src: "https://app.polyquity.org/favicon.png" },
  { name: "Tako", src: "https://takodefi.com/favicon.ico" },
  { name: "Harvester", src: "https://harvester.app/favicon.png" },
  { name: "Polymer", src: "https://polymeryield.finance/favicon.ico" },
  { name: "Polybrew", src: "https://polybrew.finance/favicon.ico" },
  { name: "PolyDiamond", src: "https://polydiamondfinance.com/favicon.ico" },
  { name: "PolyCactus", src: "https://polycactus.com/favicon.ico" },
  { name: "PolyGrass", src: "https://polygrass.online/favicon.ico" },
  { name: "Pickle", src: "https://app.pickle.finance/favicon.ico" },
  { name: "Fox", src: "https://foxfarming.us/favicon.ico" },
  { name: "MountainSwap", src: "                     /favicon.ico" },
  { name: "Hippolygon", src: "https://hippolygon.com/favicon.ico" },
  { name: "Pepe", src: "https://pepefarm.finance/favicon.png" },
  { name: "PolyPupBone", src: "https://bone.polypup.finance/favicon.ico" },
  { name: "PolyRhino", src: "https://polyrhino.vercel.app/favicon.ico" },
  { name: "PolyRuby", src: "https://www.polyruby.finance/favicon.ico" },
  { name: "PolyZeus", src: "https://polyzeus.finance/favicon.ico" },
  {
    name: "PolyMax - CaveMan",
    src: "https://caveman.polymax.club/favicon.ico",
  },
  {
    name: "PolyTreasure",
    src: "https://vfat.tools/polygon/polytreasure/favicon.ico",
  },
  { name: "PolyRacoon", src: "https://polyracoon.com//favicon.ico" },
  { name: "BoneSwap", src: "https://farm.boneswap.finance/favicon.ico" },
  { name: "Polyyearn", src: "https://polyyearn.finance/favicon.ico" },
  {
    name: "WorldSwap Hanoi",
    src: "https://hanoi.worldswap.finance/favicon.ico",
  },
  { name: "Astrobunny", src: "https://www.astrobunny.finance/favicon.ico" },
  { name: "BisonFinance", src: "https://bisonfinance.online/favicon.ico" },
  { name: "Bullrun", src: "https://polygon.bullrun.finance/favicon.ico" },
  { name: "PolyArrow", src: "https://polyarrow.xyz/favicon.ico" },
  { name: "PantsuSwap", src: "https://pantsuswap.com/favicon.ico" },
  { name: "PolyMocha", src: "https://polymocha.finance/favicon.ico" },
  { name: "PolyOwl", src: "https://www.polyowl.finance/favicon.ico" },
  {
    name: "Astrofarms - Cancer",
    src: "https://cancer.astrofarms.finance/favicon.ico",
  },
  { name: "FaunaFinance", src: "https://www.fauna.finance/favicon.ico" },
  { name: "Vampire", src: "https://vampirefarming.club/favicon.ico" },
  { name: "PolyGorilla", src: "https://polygorilla.finance/favicon.ico" },
  { name: "PolyGarden", src: "https://www.polygarden.finance/favicon.ico" },
  { name: "Gains Farm", src: "https://gains.farm/favicon.ico" },
  { name: "DojoFarmFinance", src: "https://dojofarm.finance/favicon.ico" },
  {
    name: "PolyMaple-MapleSyrup",
    src: "https://www.polymaple.com/favicon.ico",
  },
  { name: "PolyTopia", src: "https://polytopia.farm/favicon.ico" },
  { name: "BrainSwap", src: "https://brainswap.finance/favicon.ico" },
  { name: "BatSwap", src: "https://batswap.finance/favicon.ico" },
  { name: "ChickenFarms", src: "https://chickenfarms.live/favicon.ico" },

  { name: "Levin", src: "https://farm.levinswap.org/favicon.png" },
  { name: "Swapr", src: "https://swapr.eth.link/favicon.png" },

  { name: "Pangolin", src: "https://app.pangolin.exchange/favicon.png" },
  { name: "Complus", src: "https://avax.complus.exchange/favicon.png" },
  { name: "Zero", src: "https://app.0.exchange/favicon.png" },
  { name: "Yeti", src: "https://exchange.yetiswap.app/favicon.png" },
  { name: "Pandaswap", src: "https://pandaswap.exchange/favicon.ico" },
  { name: "Pefi *", src: "https://penguinfinance.org/favicon.ico" },
  { name: "Elk", src: "https://elk.finance/favicon.ico" },
  { name: "Snowball", src: "https://snowball.network/favicon.ico" },
  { name: "Olive", src: "https://avax.olive.cash/favicon.ico" },
  { name: "Lydia", src: "https://www.lydia.finance/favicon.ico" },
  { name: "Baguette", src: "https://app.baguette.exchange/favicon.png" },
  { name: "Gondola", src: "https://app.gondola.finance/favicon.ico" },
  { name: "Birdy", src: "https://birdy.finance/favicon.ico" },
  { name: "Canary", src: "https://app.canary.exchange/favicon.png" },
  { name: "Avalaunch", src: "https://farm.avalaunch.app/assets/favicon.ico" },
  { name: "Avme", src: "https://avme.io/favicon.ico" },

  { name: "Popsicle", src: "https://popsicle.finance/favicon.ico" },
  { name: "Spooky", src: "https://spookyswap.finance/favicon.ico" },
  { name: "Spirit", src: "https://app.spiritswap.finance/favicon.ico" },
  { name: "Borg", src: "https://ftm.borgswap.exchange/favicon.ico" },
  { name: "Hyperjump", src: "https://hyperjump.fi/favicon.ico" },
  { name: "Ester", src: "https://ester.finance/favicon.ico" },
  { name: "Froyo", src: "https://frozenyogurt.finance/favicon.ico" },
  { name: "Ghost", src: "https://www.theghost.finance/favicon.png" },
  { name: "Beefy", src: "https://fantom.beefy.finance/favicon.ico" },
  {
    name: "Liquid Driver",
    src: "https://www.liquiddriver.finance/favicon.ico",
  },
  { name: "Mushrooms", src: "https://mushrooms.finance/farms/favicon.ico" },
  { name: "Greenhouse", src: "https://thegreenhouse.finance/favicon.ico" },
  { name: "Stake Steak", src: "https://stakesteak.com/favicon.ico" },
  { name: "Frankenstein", src: "https://frankenstein.finance/favicon.ico" },
  { name: "Waka", src: "https://waka.finance/favicon.ico" },
  { name: "Elk", src: "https://app.elk.finance/favicon.ico" },
  { name: "Paintswap", src: "https://paintswap.finance/favicon.png" },
  { name: "Tomb", src: "https://tomb.finance/favicon.ico" },
  { name: "Shadow", src: "https://shadowswap.app/favicon.ico" },
  { name: "Borgswap", src: "https://klingftm.borgswap.exchange/favicon.ico" },
  { name: "Opera", src: "https://www.operaswap.finance/favicon.ico" },
  { name: "Chad", src: "N/A/favicon.ico" },
  { name: "Guru", src: "https://ftm.guru/img/ftm1337.jpg" },
  { name: "Rediant", src: "https://rediant.finance/favicon.ico" },
  { name: "Mlnl", src: "https://milfinance.xyz/favicon.ico" },
  {
    name: "Yorocoon",
    src: "https://yorocoon.com/wp-content/uploads/2021/06/cropped-CATY88-90x75.png",
  },
  { name: "Balloon Farms", src: "https://www.fantomballoons.com/favicon.ico" },
  { name: "Spoon", src: "https://app.spoon.finance/favicon.ico" },
  { name: "Bullrun", src: "https://fantom.bullrun.finance/favicon.ico" },
  { name: "Strangebrew", src: "https://www.strangebrew.finance/favicon.ico" },
  { name: "Uniron", src: "https://www.uniron.finance/assets/img/logo.png" },

  { name: "Viper", src: "https://viper.exchange/favicon.png" },
  { name: "Open Swap", src: "https://app.openswap.one/favicon.ico" },
  { name: "Loot", src: "https://lootswap.finance/favicon.png" },
  {
    name: "Daikiri",
    src: "https://daikiri.finance/img/favicon/favicon-32x32.png",
  },

  { name: "Fuseswap", src: "https://fuseswap.com/favicon.png" },

  { name: "Ram Protocol", src: "https://rammer.finance//favicon.ico" },

  { name: "KuSwap", src: "https://kuswap.io/metas/favicon-32x32.png?v=kuu2" },
  { name: "KuCat", src: "https://kucat.finance/favicon.ico" },
  { name: "KuBeans", src: "https://kubeans.club/favicon.png" },
];
